# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeApiserverProxy < Formula
  desc "kube-apiserver-proxy binary"
  homepage "https://github.com/omissis/kube-apiserver-proxy"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omissis/kube-apiserver-proxy/releases/download/v0.2.0/kube-apiserver-proxy-darwin-arm64.tar.gz"
      sha256 "8b5baea5ce821355e1e8f0677810900e1466da8d5df89782a4d4d43fbf0b7532"

      def install
        bin.install 'kube-apiserver-proxy'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omissis/kube-apiserver-proxy/releases/download/v0.2.0/kube-apiserver-proxy-darwin-amd64.tar.gz"
      sha256 "dbaa342f94a1cba6ec636226f788b0a0966d3db94778da15093a7e9ec1100baf"

      def install
        bin.install 'kube-apiserver-proxy'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omissis/kube-apiserver-proxy/releases/download/v0.2.0/kube-apiserver-proxy-linux-arm64.tar.gz"
      sha256 "e5eecef773987f1b4783ad98b25459e648c1964680d0366115d7119bafad6a87"

      def install
        bin.install 'kube-apiserver-proxy'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omissis/kube-apiserver-proxy/releases/download/v0.2.0/kube-apiserver-proxy-linux-amd64.tar.gz"
      sha256 "43ae252658e05077533a1264476316826c2afef3e51b5231a6f57c1091a2b1cf"

      def install
        bin.install 'kube-apiserver-proxy'
      end
    end
  end

  test do
    system "#{bin}/kube-apiserver-proxy"
  end
end
